version: '2'
services:
  rabbit-node-1:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 1000
      recreate_on_quorum_strategy_config:
        quorum: 1
      port: 15672
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      request_line: GET "/" "HTTP/1.0"
      reinitializing_timeout: 60000
  rabbit-node-2:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 1000
      recreate_on_quorum_strategy_config:
        quorum: 1
      port: 15672
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      request_line: GET "/" "HTTP/1.0"
      reinitializing_timeout: 60000
